# run: conda env create --file lava_environment.yml
# include new packages: conda env update --file lava_environment.yml
name: lava
channels:
  - conda-forge
  - conda
dependencies:
- anaconda
- conda:
# Run python tests.
  - pytest=6.1.2
- pip
- pip:
# Auto generate docstrings
  - pyment
# Get Lava repository from GitHub.
#  - git+https://github.com/lava-nc/lava.git
# Run pip install on .tar.gz file in GitHub repository.
  - https://github.com/lava-nc/lava/releases/download/v0.3.0/lava-nc-0.3.0.tar.gz
